title: Tutorial buscar-pubmed
description: Domina búsquedas bibliográficas clínicas en 5 minutos
baseurl: "/buscar-pubmed-tutorial" # Ruta base: ¡esto es CLAVE para que funcionen los estilos en GitHub Pages!
url: "https://ernestobarrera.github.io" # No pongas la ruta del repo aquí, solo el dominio
repository: ernestobarrera/buscar-pubmed-tutorial # Tu repo real para los enlaces a GitHub

# Just the Docs como tema remoto (mejor práctica en GitHub Pages)
remote_theme: just-the-docs/just-the-docs

permalink: pretty

# Exclusiones estándar
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - docker-compose.yml
  - Dockerfile
  - fixtures/

# Logo opcional (actívalo si subes tu logo)
#logo: "/assets/images/tu-logo.png"

# Búsqueda interna activa y personalizada
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: "k"

# Copiar código con botón
enable_copy_code_button: true

# Mermaid opcional (si usas diagramas)
# mermaid:
#   version: "9.1.6"

# Enlaces auxiliares (arriba a la derecha)
aux_links:
  "🔍 Herramienta buscar-pubmed":
    - "https://ernestobarrera.github.io/buscar-pubmed.html"
  "🤖 GPT Asistente":
    - "https://chatgpt.com/g/g-679fc8b5a99481919ee408d9c064f2ed-pubmed-help-asistente-para-busquedas-avanzadas"

aux_links_new_tab: true

# Menú lateral activo y orden alfabético
nav_enabled: true
nav_sort: case_insensitive # O puedes quitarlo para el orden por nav_order

# Enlaces externos de navegación
nav_external_links:
  - title: "🔍 Herramienta buscar-pubmed"
    url: "https://ernestobarrera.github.io/buscar-pubmed.html"
  - title: "🤖 GPT Asistente"
    url: "https://chatgpt.com/g/g-679fc8b5a99481919ee408d9c064f2ed-pubmed-help-asistente-para-busquedas-avanzadas"

# Footer y edición GitHub
footer_content: 'Copyright &copy; 2025 Ernesto Barrera. Tutorial bajo <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>'
back_to_top: true
back_to_top_text: "Volver arriba"
last_edit_timestamp: true
last_edit_time_format: "%d/%m/%Y %H:%M"
gh_edit_link: true
gh_edit_link_text: "Editar esta página en GitHub"
gh_edit_repository: "https://github.com/ernestobarrera/buscar-pubmed-tutorial"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

color_scheme: light # O "dark" si quieres forzarlo

# Callouts (personaliza si quieres mensajes destacados)
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Importante
    color: blue
  new:
    title: Nuevo
    color: green
  note:
    title: Nota
    color: purple
  warning:
    title: Aviso
    color: red

# Plugins recomendados (los de GitHub Pages y Just the Docs)
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Opcional: errores estrictos para liquid
liquid:
  error_mode: strict
  strict_filters: true
